$content = Get-Content 'C:\Users\casa\Downloads\Beci2ver\Favoritosbeci.html' -Raw -Encoding UTF8

# Remove the wrapper div that constrains the header
$content = $content -replace '<div class="w-full max-w-screen-xl mx-auto h-screen relative flex flex-col shadow-2xl overflow-hidden bg-white/10 lg:bg-transparent lg:shadow-none">', ''

# Replace the header with the exact HomeBeci header (as direct child of body)
$oldHeader = '<header class="desktop-header fixed top-0 left-0 w-full h-\[80px\] bg-white shadow-\[0_4px_20px_rgba\(0,0,0,0.15\)\] z-\[100\] items-center justify-between px-8\"><div class="h-\[6.15rem\] w-\[10.35rem\] bg-contain bg-no-repeat bg-center" style="background-image: url('\''img/Logobeci.png'\'')"></div><nav class="flex items-center gap-12"><a class="font-poppins text-\[16px\] font-semibold text-\[#4b5563\] hover:text-\[#5329C3\] relative after:content-['''] after:absolute after:bottom-\[-5px\] after:left-0 after:w-full after:h-\[3px\] after:bg-\[#5329C3\] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="HomeBeci.html">Inicio</a><a class="font-poppins text-\[16px\] font-extrabold text-\[#5329C3\] relative after:content-['''] after:absolute after:bottom-\[-5px\] after:left-0 after:w-full after:h-\[4px\] after:bg-\[#5329C3\] after:rounded-full after:origin-left after:scale-x-100 after:transition-transform after:duration-300" href="Favoritosbeci.html">Tus Favoritos</a><a class="font-poppins text-\[16px\] font-semibold text-\[#4b5563\] hover:text-\[#5329C3\] relative after:content-['''] after:absolute after:bottom-\[-5px\] after:left-0 after:w-full after:h-\[3px\] after:bg-\[#5329C3\] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="Sobrebeci.html">Sobre Beci</a><a class="font-poppins text-\[16px\] font-semibold text-\[#4b5563\] hover:text-\[#5329C3\] relative after:content-['''] after:absolute after:bottom-\[-5px\] after:left-0 after:w-full after:h-\[3px\] after:bg-\[#5329C3\] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="TeAyudamosBeci.html">¿Te ayudamos?</a><a class="font-poppins text-\[16px\] font-semibold text-\[#4b5563\] hover:text-\[#5329C3\] relative after:content-['''] after:absolute after:bottom-\[-5px\] after:left-0 after:w-full after:h-\[3px\] after:bg-\[#5329C3\] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="Perfilbeci.html">Vecino</a></nav></header>'

$newHeader = '<header class="desktop-header fixed top-0 left-0 w-full h-[80px] bg-white shadow-[0_4px_20px_rgba(0,0,0,0.15)] z-[100] items-center justify-between px-8"><div class="h-[6.15rem] w-[10.35rem] bg-contain bg-no-repeat bg-center" style="background-image: url('\''img/Logobeci.png'\'')"></div><nav class="flex items-center gap-12"><a class="font-poppins text-[16px] font-semibold text-[#4b5563] hover:text-[#5329C3] relative after:content-['''] after:absolute after:bottom-[-5px] after:left-0 after:w-full after:h-[3px] after:bg-[#5329C3] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="HomeBeci.html">Inicio</a><a class="font-poppins text-[16px] font-extrabold text-[#5329C3] relative after:content-['''] after:absolute after:bottom-[-5px] after:left-0 after:w-full after:h-[4px] after:bg-[#5329C3] after:rounded-full after:origin-left after:scale-x-100 after:transition-transform after:duration-300" href="Favoritosbeci.html">Tus Favoritos</a><a class="font-poppins text-[16px] font-semibold text-[#4b5563] hover:text-[#5329C3] relative after:content-['''] after:absolute after:bottom-[-5px] after:left-0 after:w-full after:h-[3px] after:bg-[#5329C3] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="Sobrebeci.html">Sobre Beci</a><a class="font-poppins text-[16px] font-semibold text-[#4b5563] hover:text-[#5329C3] relative after:content-['''] after:absolute after:bottom-[-5px] after:left-0 after:w-full after:h-[3px] after:bg-[#5329C3] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="TeAyudamosBeci.html">¿Te ayudamos?</a><a class="font-poppins text-[16px] font-semibold text-[#4b5563] hover:text-[#5329C3] relative after:content-['''] after:absolute after:bottom-[-5px] after:left-0 after:w-full after:h-[3px] after:bg-[#5329C3] after:rounded-full after:origin-left after:scale-x-0 after:transition-transform after:duration-300 hover:after:scale-x-100" href="Perfilbeci.html">Vecino</a></nav></header>'

$content = $content -replace [regex]::Escape($oldHeader), $newHeader

Set-Content 'C:\Users\casa\Downloads\Beci2ver\Favoritosbeci.html' -Value $content -Encoding UTF8